repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8 (style)
        entry: python -m flake8
        args: [.]
        language: system
        pass_filenames: false
        always_run: true

      - id: bandit
        name: bandit (security scan)
        entry: python -m bandit
        args: [-r, helpers/, ibtool_tools/, ibtool/, __init__.py, -ll]
        language: system
        pass_filenames: false
        always_run: true

      - id: detect-secrets
        name: detect-secrets (secret scan)
        entry: detect-secrets-hook
        args: [--baseline, .secrets.baseline]
        language: system
        types: [python]
