# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IBTool
                                 A QGIS plugin
 Toolset for the delineation of settlements on the basis
of building footprints
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-18
        copyright            : (C) 2024 by Oliver Harig
        email                : ottmar.hittzfeld@web.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


import sys as _sys
import os as _os
import types as _types

# The plugin folder on Windows is 'IB-Tool-3', not 'ibtool'.
# ibtool/ibtool.py uses absolute imports like `from ibtool.helpers.x import y`.
# Register a virtual 'ibtool' package so those imports resolve correctly.
_plugin_root = _os.path.dirname(_os.path.abspath(__file__))
if 'ibtool' not in _sys.modules:
    _mod = _types.ModuleType('ibtool')
    _mod.__path__ = [_plugin_root]
    _mod.__package__ = 'ibtool'
    _mod.__file__ = __file__
    _sys.modules['ibtool'] = _mod


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load IBTool class from file IBTool.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ibtool.ibtool import IBTool
    return IBTool(iface)
