[ibtool]
# default paths for GUI
hu_path = Testdaten/A_HU.shp
rn_path = Testdaten/A_RN.shp
part_path = Testdaten/A_PART.shp
aux_path = Testdaten/A_AUX.shp
output_path = Testdaten/output.gpkg
workspace_path = Testdaten/workspace
filter_path = Testdaten/IB-Tool2_Filter.txt
log_dir = Testdaten/logs

# default numeric parameters
min_overlap_blocks = 18
global_footprint_density = 0
min_area = 57
min_bdg_count = 20
min_patch_size = 10000
max_hole_size = 10000
max_gap_size = 4900
part_start = -1
part_end = -1
part_list = #
spatial_reference = EPSG:25833
log_level = INFO
delete_part_log = True
