# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IBTool
                                 A QGIS plugin
 Toolset for the delineation of settlements on the basis
of building footprints
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-12-18
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Oliver Harig
        email                : ottmar.hittzfeld@web.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""


from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QThread, pyqtSignal
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog, QDialog

from qgis.core import (
    QgsProject,
    Qgis,
    QgsApplication,
    QgsProcessingFeedback,
    QgsVectorFileWriter,
    #QgsVectorLayer,
    QgsVectorDataProvider,
    QgsRasterLayer,
    QgsProcessingAlgorithm,
    QgsProcessingParameterFeatureSource,
    QgsProcessingParameterNumber,
    QgsProcessingParameterFeatureSink,
    QgsProcessingParameterFileDestination,
    QgsProcessingUtils,
    QgsCoordinateReferenceSystem,
    QgsExpression,
    QgsProcessingFeatureSourceDefinition,
    QgsFeature,
    QgsProcessing
)

from qgis import processing


from .helpers.logger import Logger
# Initialisieren Sie den Logger
logger = Logger()

from .helpers.geometry_utils import (
    polyline2,
    check_projection,
    load_to_geopackage,
    select_and_save_by_location,
    create_polygons_from_lines

)
from .helpers.data_loader import *
from .helpers.system_utils import (
    #log,
    #set_log_level_from_combobox,
    manage_directory,
    save_temp_layer_to_gpkg,
    copy_shapefile
)
from .helpers.message import msg
from .helpers.system_utils import get_feature_count

from .ibtool_tools.FootprintDensity import calc_footprint_density, identify_dense_blocks
from .ibtool_tools.Blocker import blocker
from .ibtool_tools.ImportFilter import input_hu_filter
from .ibtool_tools.CreateMST import calculate_mst
from .ibtool_tools.MST_Clustering import mst_clustering
from .ibtool_tools.AddSingleBuilding import add_single_bdg
from .ibtool_tools.EdgeCatch import edge_catch

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .ibtool_dialog import IBToolDialog
import os.path
import time
import sys
import datetime
import shutil

os.environ['PYTHONPATH'] = '/helpers'
sys.path.append(os.environ['PYTHONPATH'])

class ProcessingThread(QThread):
    """Thread für die Verarbeitung im Hintergrund"""
    progress_update = pyqtSignal(int)
    log_message = pyqtSignal(str)

    def run(self):
        """Hauptverarbeitungslogik"""
        try:
            for i in range(101):  # Fortschritt von 0 bis 100
                self.msleep(50)  # Simulierte Verarbeitung (50 ms Verzögerung)
                self.progress_update.emit(i)  # Fortschritt aktualisieren
                self.log_message.emit(f"Fortschritt: {i}%")  # Nachricht senden
        except Exception as e:
            self.log_message.emit(f"Fehler: {str(e)}")

class IBTool:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'IBTool_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&IB-Tool')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

        """Initialisierung der Hauptklasse"""
        # Erstellen einer neuen Instanz der generierten UI-Klasse
        self.dlg = IBToolDialog()

        # Verbindung der UI mit einem QDialog-Objekt
        self.dialog = QDialog()  # Ein neues QDialog-Objekt erzeugen
        self.dlg.setupUi(self.dialog)  # Die UI mit dem Dialog verknüpfen

        # Hinzufügen von ProgressBar und Nachrichtenfenster
        self.dlg.ProgressBar.setValue(0)  # Fortschritt auf 0 setzen
        self.dlg.MessageBox.clear()  # Nachrichtenfenster leeren

        # Thread für Hintergrundprozess
        self.thread = ProcessingThread()
        self.thread.progress_update.connect(self.update_progress)
        self.thread.log_message.connect(self.update_messages)

    def run(self):
        """Callback-Methode für den Plugin-Start."""
        msg("Plugin wurde ausgeführt")
        # Hier kann der Code hinzugefügt werden, um den Dialog oder andere Elemente zu starten

    def update_progress(self, value):
        """Fortschrittsbalken aktualisieren"""
        self.dlg.ProgressBar.setValue(value)

    def update_messages(self, message):
        """Nachrichten im Fenster anzeigen"""
        self.dlg.MessageBox.appendPlainText(message)

    def cancel_processing(self):
        """Verarbeitung abbrechen"""
        if self.thread.isRunning():
            self.thread.terminate()  # Thread beenden
            self.update_messages("Verarbeitung abgebrochen.")

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('IBTool', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/ibtool/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'IB-Tool'),
            callback=self.run,
            parent=self.iface.mainWindow())

        self.setup_logging_in_plugin() # logging der UI deaktivert

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&IB-Tool'),
                action)
            self.iface.removeToolBarIcon(action)

        # Logger schließen
        logger.close_logger()

    def setup_logging_in_plugin(self):
        """
        Verbindet die QComboBox zur Steuerung des Log-Levels.
        """
        valid_levels = ['INFO', 'WARNING', 'CRITICAL', 'SUCCESS']
        self.dlg.LogLevelBox.addItems(valid_levels)

        # Standard-Log-Level setzen
        default_level = 'INFO'
        if default_level in valid_levels:
            self.dlg.LogLevelBox.setCurrentText(default_level)
            logger.set_log_level(default_level)
        else:
            raise ValueError(f"Ungültiger Standard-Log-Level: {default_level}")

        # Log-Level-Wechsel behandeln
        def apply_log_level():
            selected_level = self.dlg.LogLevelBox.currentText()
            if selected_level in valid_levels:
                logger.set_log_level(selected_level)
            else:
                msg(f"Ungültiger Log-Level: {selected_level}")

        self.dlg.LogLevelBox.currentTextChanged.connect(apply_log_level)

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = IBToolDialog()
            self.dlg.HuButton.clicked.connect(select_HU_file)
            self.dlg.RnButton.clicked.connect(select_RN_file)
            self.dlg.PartButton.clicked.connect(select_PART_file)
            self.dlg.AuxButton.clicked.connect(select_AUX_file)
            self.dlg.OutputButton.clicked.connect(select_output_file)
            self.dlg.WorkspaceButton.clicked.connect(select_workspace_file)
            self.dlg.FilterButton.clicked.connect(self.select_filter_file)
            self.dlg.StartButton.clicked.connect(self.start_processing)
            self.dlg.CancelButton.clicked.connect(self.cancel_processing)
            self.dlg.LogLevelBox.currentTextChanged.connect(
                lambda: logger.set_log_level(self.dlg.LogLevelBox.currentText())
            )

        # Automatische Aktualisierung der Textfelder bei Start
        file_path = self.dlg.FilterPath.text()  # Pfad aus dem QLineEdit abrufen
        if file_path and os.path.exists(file_path):  # Prüfen, ob Pfad existiert
            self.load_filter_file(file_path)  # Datei laden und Textfelder aktualisieren
            
        logger.set_message_box(self.dlg.MessageBox)

        self.dlg.MessageBox.clear()
        # show the dialog
        self.dlg.show()

    def select_filter_file(self):
        """Öffnet einen Dateidialog, um die Filterdatei auszuwählen, und verarbeitet sie."""
        file_path, _ = QFileDialog.getOpenFileName(
            self.dlg,  # Dialog ist Teil der GUI
            "Filter-Datei auswählen",
            "",
            "Text-Dateien (*.txt);;Alle Dateien (*)"
        )
        if file_path:
            self.dlg.FilterPath.setText(file_path)  # Zeige den Pfad in QLineEdit an
            self.load_filter_file(file_path)  # Lade und verarbeite die Filterdatei

    def load_filter_file(self, file_path):
        """Liest die Filterdatei und zeigt die Filter in der GUI an."""
        try:
            with open(file_path, 'r', encoding='utf-8') as file:
                lines = file.readlines()

            # Filter extrahieren
            positive_filters = []
            negative_filters = []
            current_section = None

            for line in lines:
                line = line.strip()
                if line.startswith("#Filter positive"):
                    current_section = "positive"
                elif line.startswith("#Filter negative"):
                    current_section = "negative"
                elif line.startswith("#") or not line:
                    continue
                else:
                    if current_section == "positive":
                        positive_filters.append(line)
                    elif current_section == "negative":
                        negative_filters.append(line)

            # Zeige die Filter in der GUI an (z. B. Textfelder in deinem Dialog)
            self.dlg.txtPositive.setPlainText("\n".join(positive_filters))
            self.dlg.txtNegative.setPlainText("\n".join(negative_filters))

            logger.log("Filterdatei erfolgreich geladen.", level="INFO")

        except Exception as e:
            logger.log(f"Fehler beim Laden der Filterdatei: {str(e)}", level="CRITICAL")

    def start_processing(self):
        """Hauptprozess starten"""

        logger.log("Hauptprozess wird gestartet...", level="INFO")
        # Füge hier die Logik deines Hauptprozesses ein
        self.dlg.ProgressBar.setValue(0)  # Fortschritt auf 0 setzen

        logger.log("Dies ist eine kritische Nachricht.", level="CRITICAL")
        logger.log("Dies ist eine Warnung.", level="WARNING")
        logger.log("Dies ist eine Info.", level="INFO")
        logger.log("Dies ist eine Debug-Nachricht.", level="SUCCESS")

        global startzeit
        global lockswitch
        global partlist

        global PartLogPath

        Workspace = os.getcwd()
        os.chdir(Workspace)




        MinOverlapBlocks= self.dlg.MinOverlapBlocksBox.text()
        try:
            MinOverlapBlocks = int(MinOverlapBlocks)  # Konvertiere den Text in eine Zahl
        except ValueError:
            logger.log("Ungültiger Zahlenwert eingegeben.")

        GlobalFootprintDensity = self.dlg.GlobalFootprintDensityBox.text()
        try:
            GlobalFootprintDensity = int(GlobalFootprintDensity)
        except ValueError:
            logger.log("Ungültiger Zahlenwert für Global Footprint Density eingegeben.")

        MinArea = self.dlg.MinAreaBox.text()
        try:
            MinArea = float(MinArea)
        except ValueError:
            logger.log("Ungültiger Zahlenwert für MinArea eingegeben.")

        MinBdgCount = self.dlg.MinBdgCountBox.text()
        try:
            MinBdgCount = int(MinBdgCount)
        except ValueError:
            logger.log("Ungültiger Zahlenwert für MinBdgCount eingegeben.")

        MinPatchSize = self.dlg.MinPatchSizeBox.text()
        try:
            MinPatchSize = float(MinPatchSize)
        except ValueError:
            logger.log("Ungültiger Zahlenwert für MinPatchSize eingegeben.")

        MaxHoleSize = self.dlg.MaxHoleSizeBox.text()
        try:
            MaxHoleSize = float(MaxHoleSize)
        except ValueError:
            logger.log("Ungültiger Zahlenwert für MaxHoleSize eingegeben.")

        MaxGapSize = self.dlg.MaxGapSizeBox.text()
        try:
            MaxGapSize = float(MaxGapSize)
        except ValueError:
            logger.log("Ungültiger Zahlenwert für MaxGapSize eingegeben.")

        partstart = int(self.dlg.partstartBox.text())
        partend = int(self.dlg.partendBox.text())
        partlist = self.dlg.partlistBox.text()
        PathCommonWorkspace = self.dlg.WorkspacePath.text()
        DelPartLog = self.dlg.PartLogBox.isChecked()
        SpatialReference = self.dlg.SpatialReferenceBox.text()
        SpatialReference = QgsCoordinateReferenceSystem(SpatialReference)
        logger.log("SpatialReference: {}".format(SpatialReference.authid()), 'INFO',)

        if partlist[0] != "#":
            partlist = list(partlist.split(","))

        manage_directory(PathCommonWorkspace, DelPartLog)

        PartLogPath = PathCommonWorkspace + 'IB_Tool_Results' + os.path.sep + 'IB_Tool2_Log.txt'
        PartLogFin = PathCommonWorkspace + 'IB_Tool_Results' + os.path.sep + "IB_Tool2_Log_Fin.txt"

        # Pfade zu den Eingabe-Shapefiles
        InputHU = self.dlg.HuPath.text()
        InputRN = self.dlg.RnPath.text()
        InputAux = self.dlg.AuxPath.text()
        InputPart = self.dlg.PartPath.text()
        InputFilter = self.dlg.FilterPath.text()

        check_projection(SpatialReference, [InputHU, InputRN, InputAux, InputPart])

        # Alle Eingabe-Shapefiles in das GeoPackage laden

        LayerRN = load_to_geopackage(InputRN, PathCommonWorkspace + "LayerRN.gpkg", "LayerRN", SpatialReference)

        LayerAux  = load_to_geopackage(InputAux, PathCommonWorkspace + "LayerAux.gpkg", "LayerAux", SpatialReference)

        LayerPart = load_to_geopackage(InputPart, PathCommonWorkspace + "LayerPart.gpkg", "LayerPart", SpatialReference)

        LayerHU= load_to_geopackage(InputHU, PathCommonWorkspace + "LayerHU.gpkg","LayerHU", SpatialReference)



        startzeit = time.strftime("%Y_%m_%d_%H_%M")
        lockswitch = False
        aux_layers_poly, aux_layers_line = create_auxiliary_data(LayerAux, LayerRN)

        # Partitionen aus Gesamtdatei für Debugging auswählen
        partlist = create_partitions_list(LayerPart, partlist, partstart, partend)
        logger.log("Partlist: {}".format(partlist), 'SUCCESS')

        '''
        # calculate threshold value for footprint density
        if GlobalFootprintDensity == 0:
            GlobalFootprintDensity = calc_footprint_density(
                LayerHU,
                LayerRN,
                100,
                0,
                'global',
                MinBdgCount,
                LayerPart)
        else:
            pass
        '''
        GlobalFootprintDensity = 18 #spaeter löschen
        logger.log("Global building coverage threshold = {}".format(str(GlobalFootprintDensity)), "INFO")

        if DelPartLog == 'True':
            if os.path.isfile(PartLogPath):
                os.remove(PartLogPath)

            Partlog = open(PartLogFin, 'w')
            Partlog.write("")
            Partlog.close()

        if not os.path.isfile(PartLogPath):
            Partlog = open(PartLogPath, 'w')
            Partlog.write("")
            Partlog.close()

        lenpartlist = len(partlist)
        anz_hu_gesamt = LayerHU.featureCount()
        anz_hu_sum = 0
        for i in partlist:
            logger.log("Check if {} is in Partlist.".format(str(i)), 'SUCCESS')
            a = 0
            isin = False
            Partlog = open(PartLogPath, 'r+')
            for row in Partlog:
                part = str(row).replace('\n', '')
                if part == i:
                    isin = True
                a = a + 1
            if isin is False:
                Partlog.write("\n" + i)
                Partlog.close()
            if isin is True:
                Partlog.close()
                logger.log("{} is in PartLog.".format(str(i)), 'SUCCESS')
                continue

            global Part_Name
            Part_Name = i
            logger.log( "#######################################################################################", 'INFO')
            logger.log( "PARTITION: " + str(Part_Name) + " - " + str(a) + " of " + str(len(partlist)), 'INFO')

            # Partition auswählen
            LayerPart.selectByExpression(f"\"NAME\" = '{Part_Name}'")

            SelPart_layer = processing.run(
                "native:saveselectedfeatures",{
                    'INPUT': LayerPart,
                    'OUTPUT': 'TEMPORARY_OUTPUT'
                })['OUTPUT']
            save_temp_layer_to_gpkg(SelPart_layer, "SelPart_{}".format(Part_Name))

            # Gebäude-Features selektieren
            SelHU_layer = select_and_save_by_location(LayerHU, SelPart_layer)
            save_temp_layer_to_gpkg(SelHU_layer, "SelHU_{}".format(Part_Name))

            # Anzahl der ausgewählten Gebäude prüfen
            anz_hu = SelHU_layer.featureCount()

            if anz_hu < 10:
                PartLogFin = os.path.join(PathCommonWorkspace, "IB_Tool_Results", "IB_Tool2_Log_Fin.txt")
                with open(PartLogFin, 'a') as Partlog:
                    Partlog.write("\n" + Part_Name)
                logger.log("Warning: No or less than 10 buildings selected in partition", 'WARNING')

            # Straßen-Features selektieren
            SelStrassen_layer = select_and_save_by_location(LayerRN, SelPart_layer)
            save_temp_layer_to_gpkg(SelStrassen_layer, "SelStrassen_{}".format(Part_Name))

            # Anzahl der ausgewählten Straßen prüfen
            anz_strassen = SelStrassen_layer.featureCount()

            if anz_strassen < 5:
                PartLogFin = os.path.join(PathCommonWorkspace, "IB_Tool_Results", "IB_Tool2_Log_Fin.txt")
                with open(PartLogFin, 'a') as Partlog:
                    Partlog.write("\n" + Part_Name)
                logger.log("Warning: No or less than 5 roads selected in partition", 'WARNING')

            aux_lines_sel = select_and_save_by_location(aux_layers_line, SelPart_layer)
            
            # Debug-Ausgaben
            logger.log("SelHU Count = {}".format(anz_hu), 'SUCCESS')
            logger.log("SelStrassen Count = {}".format(anz_strassen), 'SUCCESS')

            MinOverlapMST = calc_footprint_density(SelHU_layer, SelStrassen_layer, 100, GlobalFootprintDensity, 'local',
                                                         MinBdgCount)
            logger.log("Local building coverage =" + str(MinOverlapMST), 'SUCCESS')

            blocks = blocker(aux_layers_line, SelHU_layer, SelPart_layer)
            save_temp_layer_to_gpkg(blocks, "blocks_{}".format(Part_Name))


            HU_Filter = input_hu_filter(SelHU_layer, InputFilter, MinArea, 50, 200)
            save_temp_layer_to_gpkg(HU_Filter, "HU_Filter_{}".format(Part_Name))

            OverlapCalcOutput = calc_footprint_density(HU_Filter, aux_lines_sel, 100, MinOverlapMST, 'local', MinBdgCount)

            Blocks_dense = identify_dense_blocks(HU_Filter, blocks, OverlapCalcOutput)
            #save_temp_layer_to_gpkg(Blocks_dense, "Blocks_dense_{}".format(Part_Name))

            mst_layer = calculate_mst(HU_Filter, SelStrassen_layer, SpatialReference)
            save_temp_layer_to_gpkg(mst_layer, "MST_{}".format(Part_Name))

            hu_cluster_output = mst_clustering(hu_layer=SelHU_layer, mst_layer=mst_layer, crs = SpatialReference, overlap_ratio=GlobalFootprintDensity, )
            save_temp_layer_to_gpkg(hu_cluster_output, "hu_cluster_output")

            AddSingBdg = add_single_bdg(HU_Filter, hu_cluster_output, crs= SpatialReference, threshold=300)
            save_temp_layer_to_gpkg(AddSingBdg, "AddSingBdg")

            RectMerged = processing.run("qgis:mergevectorlayers", {
                'LAYERS': [AddSingBdg, Blocks_dense],
                'CRS': SpatialReference,
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                })['OUTPUT']
            save_temp_layer_to_gpkg(RectMerged, "RectMerged2")

            snapped_rect = edge_catch(RectMerged, HU_Filter, SelStrassen_layer, blocks, SpatialReference)
            save_temp_layer_to_gpkg(snapped_rect, "snapped_rect")

            # Fortschritt aktualisieren
            anz_hu_sum = anz_hu_sum + anz_hu
            prozent = int(anz_hu_sum / anz_hu_gesamt * 100)
            self.dlg.ProgressBar.setValue(prozent)


        logger.log("ERFOLG")
