# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IBTool
                                 A QGIS plugin
 Toolset for the delineation of settlements on the basis
of building footprints
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-12-18
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Oliver Harig
        email                : ottmar.hittzfeld@web.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import sys
import time

# Constants for configuration
PYTHONPATH = '/helpers'

def initialize_environment():
    """Set up environment variables and system paths."""
    os.environ['PYTHONPATH'] = PYTHONPATH
    sys.path.append(PYTHONPATH)

    qgis_prefix = os.environ.get('QGIS_PREFIX_PATH')
    if not qgis_prefix:
        potential_paths = [
            '/usr',
            '/usr/local',
            '/Applications/QGIS.app/Contents/MacOS'
        ]
        for path in potential_paths:
            if os.path.exists(os.path.join(path, 'bin', 'qgis')) or \
               os.path.exists(os.path.join(path, 'bin', 'qgis.bin')):
                qgis_prefix = path
                break

    if qgis_prefix:
        os.environ['PATH'] += os.pathsep + os.path.join(qgis_prefix, 'bin')
        python_path = os.path.join(qgis_prefix, 'share', 'qgis', 'python')
        os.environ['PYTHONPATH'] += os.pathsep + python_path
        if python_path not in sys.path:
            sys.path.append(python_path)

# Initialize the environment
initialize_environment()

from qgis.PyQt.QtCore import (
    QCoreApplication,
    QSettings,
    QThread,
    QTranslator,
    pyqtSignal
)
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import (
    QAction,
    QDialog
)
from qgis.core import (
    QgsCoordinateReferenceSystem,
    QgsProcessing,
    QgsApplication,
    QgsSettings,
    QgsVectorLayer
)
from qgis import processing
from ibtool.helpers.logger import Logger as MainLogger
from ibtool.helpers.geometry_utils import (
    check_projection,
    load_to_geopackage,
    select_and_save_by_location,
    create_empty_layer
)
from ibtool.helpers.system_utils import (
    manage_directory,
    save_temp_layer_to_gpkg,
    version_check
)
from ibtool.helpers.message import msg
from ibtool.helpers.check import InputValidator, ValidationResult
from ibtool.helpers.data_loader import *

from ibtool.ibtool_tools.FootprintDensity import (
    calc_footprint_density,
    identify_dense_blocks
)
from ibtool.ibtool_tools.Blocker import blocker
from ibtool.ibtool_tools.ImportFilter import input_hu_filter
from ibtool.ibtool_tools.CreateMST import calculate_mst
from ibtool.ibtool_tools.MST_Clustering import mst_clustering
from ibtool.ibtool_tools.AddSingleBuilding import add_single_bdg
from ibtool.ibtool_tools.EdgeCatch import edge_catch
from ibtool.ibtool_tools.GapClose import gap_close
from ibtool.ibtool_tools.PatchRemove import patch_remove
from ibtool.ibtool_tools.GapFix import gap_fix

# Import the dialog class
from ibtool.ibtool.ibtool_dialog import IBToolDialog

# Initialize the logger instance
logger = MainLogger()

class ProcessingThread(QThread):
    """Thread for background processing"""
    progress_update = pyqtSignal(int)
    log_message = pyqtSignal(str)

    def run(self):
        """Main processing logic"""
        try:
            for i in range(101):  # Progress from 0 to 100
                self.msleep(50)  # Simulated processing (50 ms delay)
                self.progress_update.emit(i)  # Update progress
                self.log_message.emit(f"Progress: {i}%")  # Send message
        except Exception as e:
            self.log_message.emit(f"Error: {str(e)}")

class IBTool:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.
    
        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface

        self.iface = iface
        # Initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # Initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'IBTool_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&IB-Tool')

        # Check if plugin was started the first time in the current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

        """Initialization of the main class"""
        # Create a new instance of the generated UI class
        self.dlg = IBToolDialog()

        # Link the UI to a QDialog object
        self.dialog = QDialog()  # Create a new QDialog object
        self.dlg.setupUi(self.dialog)  # Link the UI with the dialog

        # Add progress bar and message window
        self.dlg.ProgressBar.setValue(0)  # Set progress to 0
        self.dlg.MessageBox.clear()  # Clear the message window

        # Thread for background processing
        self.thread = ProcessingThread()
        self.thread.progress_update.connect(self.update_progress)
        self.thread.log_message.connect(self.update_messages)

    def run(self):
        """Callback method for the plugin start."""
        msg("Plugin executed")
        # Here you can add code to start the dialog or other elements

    def update_progress(self, value):
        """Update progress bar"""
        self.dlg.ProgressBar.setValue(value)

    def update_messages(self, message):
        """Display messages in the window"""
        self.dlg.MessageBox.appendPlainText(message)

    def cancel_processing(self):
        """Cancel processing"""
        if self.thread.isRunning():
            self.thread.terminate()  # Terminate thread
            self.update_messages("Processing canceled.")

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('IBTool', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = os.path.join(self.plugin_dir, 'icon.png')
        self.add_action(
            icon_path,
            text=self.tr(u'IB-Tool'),
            callback=self.run,
            parent=self.iface.mainWindow())

        self.setup_logging_in_plugin() # logging der UI deaktivert

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&IB-Tool'),
                action)
            self.iface.removeToolBarIcon(action)

        # Logger schließen
        logger.close_logger()

    def setup_logging_in_plugin(self):
        """
        Connects the QComboBox to control the log level.
        """
        valid_levels = ['INFO', 'WARNING', 'CRITICAL', 'SUCCESS']
        self.dlg.LogLevelBox.addItems(valid_levels)
        
        # Set the default log level
        default_level = 'INFO'
        if default_level in valid_levels:
            self.dlg.LogLevelBox.setCurrentText(default_level)
            logger.set_log_level(default_level)
        else:
            raise ValueError(f"Invalid default log level: {default_level}")

        # Handle log level changes
        def apply_log_level():
            selected_level = self.dlg.LogLevelBox.currentText()
            if selected_level in valid_levels:
                logger.set_log_level(selected_level)
            else:
                msg(f"Invalid log level: {selected_level}")

        self.dlg.LogLevelBox.currentTextChanged.connect(apply_log_level)

    def run(self):
        """Run method that performs all the real work"""

        # check version of QGIS and Python
        version_check()

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the
        # plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = IBToolDialog()
            self.dlg.HuButton.clicked.connect(self.select_HU_file)
            self.dlg.RnButton.clicked.connect(self.select_RN_file)
            self.dlg.PartButton.clicked.connect(self.select_PART_file)
            self.dlg.AuxButton.clicked.connect(self.select_AUX_file)
            self.dlg.OutputButton.clicked.connect(self.select_output_file)
            self.dlg.WorkspaceButton.clicked.connect(self.select_workspace_file)
            self.dlg.FilterButton.clicked.connect(self.select_filter_file)
            self.dlg.LogDirButton.clicked.connect(self.select_log_dir)
            self.dlg.CheckButton.clicked.connect(self.run_validation)
            self.dlg.StartButton.clicked.connect(self.start_processing)
            self.dlg.CancelButton.clicked.connect(self.cancel_processing)
            # Re-enable Start button when input paths change
            for path_widget in [self.dlg.HuPath, self.dlg.RnPath,
                                self.dlg.PartPath, self.dlg.AuxPath,
                                self.dlg.FilterPath, self.dlg.OutputPath,
                                self.dlg.WorkspacePath]:
                path_widget.textChanged.connect(
                    lambda: self.dlg.StartButton.setEnabled(True)
                )
            self.dlg.LogLevelBox.currentTextChanged.connect(
                lambda: logger.set_log_level(self.dlg.LogLevelBox.currentText())
            )

        # Automatische Aktualisierung der Textfelder bei Start
        file_path = self.dlg.FilterPath.text()  # Pfad aus dem QLineEdit abrufen
        if file_path and os.path.exists(file_path):  # Prüfen, ob Pfad existiert
            self.load_filter_file(file_path)

        logger.set_message_box(self.dlg.MessageBox)

        self.dlg.MessageBox.clear()
        # show the dialog
        self.dlg.show()

    def select_HU_file(self):
        """Opens a file dialog to select the HU file."""
        file_path, _ = QFileDialog.getOpenFileName(
            self.dlg,  # Dialog is part of the GUI
            "Select building footprints file",
            "",
            "Shapefiles (*.shp);;All Files (*)"
        )
        if file_path:
            self.dlg.HuPath.setText(file_path)  # Display the path in QLineEdit

    def select_RN_file(self):
        """Opens a file dialog to select the RN file."""
        file_path, _ = QFileDialog.getOpenFileName(
            self.dlg,
            "Select road network file",
            "",
            "Shapefiles (*.shp);;All Files (*)"
        )
        if file_path:
            self.dlg.RnPath.setText(file_path)  # Display the path in QLineEdit

    def select_PART_file(self):
        """Opens a file dialog to select the PART file."""
        file_path, _ = QFileDialog.getOpenFileName(
            self.dlg,
            "Select partitions file",
            "",
            "Shapefiles (*.shp);;All Files (*)"
        )
        if file_path:
            self.dlg.PartPath.setText(
                file_path)  # Display the path in QLineEdit

    def select_AUX_file(self):
        """Opens a file dialog to select the AUX file."""
        file_path, _ = QFileDialog.getOpenFileName(
            self.dlg,
            "Select auxiliary data file",
            "",
            "Shapefiles (*.shp);;All Files (*)"
        )
        if file_path:
            self.dlg.AuxPath.setText(file_path)

    def select_output_file(self):
        """Opens a file dialog to select or create the output file
           (GeoPackage)."""
        file_path, _ = QFileDialog.getSaveFileName(
            self.dlg,
            "Select output file",
            "",
            "GeoPackage (*.gpkg);;All Files (*)"
        )
        if file_path:
            self.dlg.OutputPath.setText(file_path)

    def select_workspace_file(self):
        """Opens a dialog to select a workspace folder."""
        folder_path = QFileDialog.getExistingDirectory(
            self.dlg,
            "Select workspace folder",
            ""
        )
        if folder_path:
            self.dlg.WorkspacePath.setText(folder_path)

    def select_filter_file(self):
        """Opens a file dialog to select the filter file
        and processes it."""
        file_path, _ = QFileDialog.getOpenFileName(
            self.dlg,  # Dialog is part of the GUI
            "Select filter config file",
            "",
            "Text files (*.txt);;All Files (*)"
        )
        if file_path:
            self.dlg.FilterPath.setText(file_path)
            self.load_filter_file(file_path)

    def select_log_dir(self):
        """Öffnet einen Dialog, um das Logverzeichnis auszuwählen."""
        folder_path = QFileDialog.getExistingDirectory(
            self.dlg,
            "Select log directory",
            ""
        )
        if folder_path:
            self.dlg.LogDirPath.setText(folder_path)

    def load_filter_file(self, file_path):
        """Reads the filter file and displays the filters in the GUI."""
        try:
            with open(file_path, 'r', encoding='utf-8') as file:
                lines = file.readlines()

            # Extract filters
            positive_filters = []
            negative_filters = []
            current_section = None

            for line in lines:
                line = line.strip()
                if line.startswith("#Filter positive"):
                    current_section = "positive"
                elif line.startswith("#Filter negative"):
                    current_section = "negative"
                elif line.startswith("#") or not line:
                    continue
                else:
                    if current_section == "positive":
                        positive_filters.append(line)
                    elif current_section == "negative":
                        negative_filters.append(line)

            # Display the filters in the GUI (e.g., text fields in your dialog)
            self.dlg.txtPositive.setPlainText("\n".join(positive_filters))
            self.dlg.txtNegative.setPlainText("\n".join(negative_filters))

            # logger.log("Filter file successfully loaded.", level="INFO")

        except Exception as e:
            logger.log(f"Error while loading the filter file: {str(e)}",
                       level="CRITICAL")
            pass

    def run_validation(self):
        """Run input validation and display results in MessageBox."""
        self.dlg.MessageBox.clear()

        spatial_reference_text = self.dlg.SpatialReferenceBox.text()
        spatial_reference = QgsCoordinateReferenceSystem(spatial_reference_text)

        validator = InputValidator()
        result = validator.validate_all(
            hu_path=self.dlg.HuPath.text(),
            rn_path=self.dlg.RnPath.text(),
            part_path=self.dlg.PartPath.text(),
            aux_path=self.dlg.AuxPath.text(),
            filter_path=self.dlg.FilterPath.text(),
            output_path=self.dlg.OutputPath.text(),
            workspace_path=self.dlg.WorkspacePath.text(),
            spatial_reference=spatial_reference,
        )

        self._display_validation_result(result)
        self.dlg.StartButton.setEnabled(result.is_valid)

    def _display_validation_result(self, result: ValidationResult) -> None:
        """Format and display validation results in the MessageBox."""
        if result.is_valid and not result.warnings:
            logger.log(
                "=== VALIDIERUNG ERFOLGREICH === "
                "Alle Eingabedaten-Checks bestanden.",
                level="INFO"
            )
            return

        if result.errors:
            logger.log(
                f"=== VALIDIERUNGSFEHLER ({len(result.errors)}) ===",
                level="CRITICAL"
            )
            for i, error in enumerate(result.errors, 1):
                logger.log(f"  [{i}] {error}", level="CRITICAL")

        if result.warnings:
            logger.log(
                f"=== WARNUNGEN ({len(result.warnings)}) ===",
                level="WARNING"
            )
            for i, warning in enumerate(result.warnings, 1):
                logger.log(f"  [{i}] {warning}", level="WARNING")

        if result.is_valid:
            logger.log(
                "Validierung bestanden (mit Warnungen). "
                "Verarbeitung kann gestartet werden.",
                level="INFO"
            )
        else:
            logger.log(
                "Validierung fehlgeschlagen. "
                "Bitte Fehler oben beheben, bevor gestartet wird.",
                level="CRITICAL"
            )

    def start_processing(self):
        """Start main process"""

        # Ensure logger uses the level selected in the GUI
        selected_level = self.dlg.LogLevelBox.currentText()
        if selected_level:
            try:
                logger.set_log_level(selected_level)
            except ValueError as e:
                msg(str(e))

        log_dir = self.dlg.LogDirPath.text()
        if log_dir:
            logger.set_log_dir(log_dir)

        self.dlg.ProgressBar.setValue(0)  # Set progress to 0

        workspace = os.getcwd()
        os.chdir(workspace)

        min_overlap_blocks= self.dlg.MinOverlapBlocksBox.text()
        try:
            # Konvertiere den Text in eine Zahl
            min_overlap_blocks = float(min_overlap_blocks) #TODO

        except ValueError:
            logger.log("Invalid numeric value entered.")

        global_footprint_density = self.dlg.GlobalFootprintDensityBox.text()
        try:
            global_footprint_density = float(global_footprint_density)
        except ValueError:
            logger.log("Invalid numeric value entered.")

        min_area = self.dlg.MinAreaBox.text()
        try:
            min_area = float(min_area)
        except ValueError:
            logger.log("Invalid numeric value entered.")

        min_bdg_count = self.dlg.MinBdgCountBox.text()
        try:
            min_bdg_count = int(min_bdg_count)
        except ValueError:
            logger.log("Invalid numeric value entered.")

        min_patch_size = self.dlg.MinPatchSizeBox.text()
        try:
            min_patch_size = float(min_patch_size)
        except ValueError:
            logger.log("Invalid numeric value entered.")

        max_hole_size = self.dlg.MaxHoleSizeBox.text()
        try:
            max_hole_size = float(max_hole_size)
        except ValueError:
            logger.log("Invalid numeric value entered.")

        max_gap_size = self.dlg.MaxGapSizeBox.text()
        try:
            max_gap_size = float(max_gap_size)
        except ValueError:
            logger.log("Invalid numeric value for max_gap_size entered.")

        part_start = int(self.dlg.partstartBox.text())
        part_end = int(self.dlg.partendBox.text())
        part_list = self.dlg.partlistBox.text()

        DelPartLog = self.dlg.PartLogBox.isChecked()
        msg(f"DelPartLog={DelPartLog}")
        spatial_reference = self.dlg.SpatialReferenceBox.text()
        spatial_reference = QgsCoordinateReferenceSystem(spatial_reference)
        logger.log("spatial_reference: {}".format(spatial_reference.authid()),
                   'INFO',)

        if part_list[0] != "#":
            part_list = list(part_list.split(","))

        workspace_path = self.dlg.WorkspacePath.text() + "/"
        msg(f"workspace_path={workspace_path}")
        manage_directory(workspace_path, DelPartLog)

        part_log_path = workspace_path + 'IB_Tool_Results/IB_Tool2_Log.txt'
        PartLogFin = workspace_path + 'IB_Tool_Results/IB_Tool2_Log_Fin.txt'

        # Pfade zu den Eingabe-Shapefiles
        input_hu = self.dlg.HuPath.text()
        InputRN = self.dlg.RnPath.text()
        InputAux = self.dlg.AuxPath.text()
        InputPart = self.dlg.PartPath.text()
        input_filter = self.dlg.FilterPath.text()
        OutputFile = self.dlg.OutputPath.text()
        msg(f"Outputfile={OutputFile}") #ToDO entfernen

        # Input validation (replaces old check_projection call)
        validator = InputValidator()
        validation_result = validator.validate_all(
            hu_path=input_hu,
            rn_path=InputRN,
            part_path=InputPart,
            aux_path=InputAux,
            filter_path=input_filter,
            output_path=OutputFile,
            workspace_path=self.dlg.WorkspacePath.text(),
            spatial_reference=spatial_reference,
        )
        self._display_validation_result(validation_result)
        if not validation_result.is_valid:
            logger.log("Verarbeitung abgebrochen wegen Validierungsfehlern.",
                       level="CRITICAL")
            return

        # Alle Eingabe-Shapefiles in das GeoPackage laden

        layer_rn = load_to_geopackage(InputRN,
                                     workspace_path + "layer_rn.gpkg",
                                    "layer_rn", spatial_reference)
        layer_rn.dataProvider().createSpatialIndex()
        layer_aux  = load_to_geopackage(InputAux,
                                       workspace_path + "layer_aux.gpkg",
                                       "layer_aux", spatial_reference)
        layer_aux.dataProvider().createSpatialIndex()
        layer_part = load_to_geopackage(InputPart,
                                       workspace_path + "layer_part.gpkg",
                                       "layer_part", spatial_reference)
        layer_part.dataProvider().createSpatialIndex()
        layer_hu= load_to_geopackage(input_hu,
                                    workspace_path + "layer_hu.gpkg",
                                    "layer_hu", spatial_reference)
        layer_hu.dataProvider().createSpatialIndex()


        startzeit = time.strftime("%Y_%m_%d_%H_%M")
        lockswitch = False

        aux_layers_line = processing.run("qgis:mergevectorlayers", {
            'LAYERS': [layer_aux, layer_rn],
            'CRS': spatial_reference,
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        })['OUTPUT']

        merge_layer = create_empty_layer("global_merge_layer",
                                         "Polygon",
                                         spatial_reference.authid())
        merge = merge_layer  # Initialize to avoid UnboundLocalError if loop doesn't execute
        # Partitionen aus Gesamtdatei für Debugging auswählen
        part_list = create_partitions_list(layer_part,
                                          part_list,
                                          part_start,
                                          part_end)

        logger.log("Part list: {}".format(part_list), 'SUCCESS')

        #global_footprint_density = 18  # TODO

        # calculate threshold value for footprint density
        if global_footprint_density == 0:
            global_footprint_density = calc_footprint_density(
                layer_hu,
                layer_rn,
                100,
                0,
                'global',
                min_bdg_count,
                layer_part)
        else:
            pass

        logger.log("Global building coverage threshold = {}".format(str(global_footprint_density)), "INFO")

        msg(part_log_path) #TODO löschen
        if DelPartLog == 'True':
            if os.path.isfile(part_log_path):
                os.remove(part_log_path)

            part_log = open(PartLogFin, 'w')
            part_log.write("")
            part_log.close()

        if not os.path.isfile(part_log_path):
            part_log = open(part_log_path, 'w')
            part_log.write("")
            part_log.close()

        anz_hu_gesamt = layer_hu.featureCount()
        anz_hu_sum = 0


        for i in part_list:
            logger.log("Check if {} is in Partlist.".format(str(i)), 
                       'SUCCESS')
            a = 1
            isin = False
            part_log = open(part_log_path, 'r+')
            for row in part_log:
                part = str(row).replace('\n', '')
                if part == i:
                    isin = True
                a = a + 1
            if isin is False:
                part_log.write("\n" + i)
                part_log.close()
            if isin is True:
                part_log.close()
                logger.log("{} is in PartLog.".format(str(i)), 'SUCCESS')
                continue

            part_name = i
            logger.log( "###############################", 'INFO')
            logger.log( "PARTITION: " + str(part_name) + " - " + str(a) + " of " 
                        + str(len(part_list)), 'INFO')

            # Partition auswählen
            sel_part_layer = processing.run(
                    "native:extractbyexpression",{
                    'INPUT': layer_part,
                    'EXPRESSION': f"\"NAME\" = '{part_name}'",
                    'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                    })['OUTPUT']

            # Gebäude-Features selektieren
            sel_hu_layer = select_and_save_by_location(layer_hu, sel_part_layer)
            save_temp_layer_to_gpkg(sel_hu_layer, "SelHU_{}".format(part_name), workspace_path)

            # Anzahl der ausgewählten Gebäude prüfen
            anz_hu = sel_hu_layer.featureCount()

            if anz_hu < 10:
                with open(PartLogFin, 'a') as part_log:
                    part_log.write("\n" + part_name)
                logger.log("Warning: No or less than 10 buildings selected in partition", 'WARNING')
                continue

            # Straßen-Features selektieren
            sel_strassen_layer = select_and_save_by_location(layer_rn, sel_part_layer)
            save_temp_layer_to_gpkg(sel_strassen_layer, "SelStrassen_{}".format(part_name),workspace_path)

            # Anzahl der ausgewählten Straßen prüfen
            anz_strassen = sel_strassen_layer.featureCount()

            if anz_strassen < 5:
                with open(PartLogFin, 'a') as part_log:
                    part_log.write("\n" + part_name)
                logger.log(f"Warning: No or less than 5 roads selected in partition {part_name}", 'WARNING')

            aux_lines_sel = select_and_save_by_location(aux_layers_line, sel_part_layer)
            save_temp_layer_to_gpkg(aux_lines_sel,
                                    f"aux_lines_sel_{str((part_name))}",
                                    workspace_path)


            # Debug-Ausgaben
            logger.log("SelHU Count = {}".format(anz_hu), 'SUCCESS')
            logger.log("SelStrassen Count = {}".format(anz_strassen), 'SUCCESS')

            min_overlap_mst = calc_footprint_density(sel_hu_layer, sel_strassen_layer, 100, global_footprint_density, 'local',
                                                         min_bdg_count)

            logger.log("Local building coverage =" + str(min_overlap_mst), 'SUCCESS')

            blocks = blocker(aux_lines_sel, sel_hu_layer, sel_part_layer)
            save_temp_layer_to_gpkg(blocks,
                                    f"blocks__{str((part_name))}",
                                    workspace_path)

            hu_filter = input_hu_filter(sel_hu_layer, input_filter,min_area, 50, 200)
            save_temp_layer_to_gpkg(hu_filter,
                                    f"hu_filter_{str((part_name))}",
                                    workspace_path)

            blocks_dense = identify_dense_blocks(hu_filter, blocks, min_overlap_blocks)
            save_temp_layer_to_gpkg(blocks_dense,
                                    f"blocks_dense_{str((part_name))}",
                                    workspace_path)

            hu_filter_sel = select_and_save_by_location(hu_filter, blocks_dense, [2], 0)
            save_temp_layer_to_gpkg(hu_filter_sel,
                                    f"hu_filter_sel_{str((part_name))}",
                                    workspace_path)

            mst_layer = calculate_mst(hu_filter_sel, sel_strassen_layer, spatial_reference)
            save_temp_layer_to_gpkg(mst_layer,
                                    f"mst_layer_{str((part_name))}",
                                    workspace_path)

            # Check if MST calculation succeeded
            if mst_layer is None:
                with open(PartLogFin, 'a') as part_log:
                    part_log.write("\n" + part_name)
                logger.log(f"MST calculation failed for partition {part_name}, skipping", 'WARNING')
                continue

            hu_cluster_output = mst_clustering(hu_filter_sel, mst_layer,spatial_reference, min_overlap_mst)
            save_temp_layer_to_gpkg(hu_cluster_output,
                                    f"hu_cluster_output_{str((part_name))}",
                                    workspace_path)

            add_sing_bdg = add_single_bdg(hu_filter_sel, hu_cluster_output, spatial_reference,  300)

            rect_merged = processing.run("qgis:mergevectorlayers", {
                'LAYERS': [add_sing_bdg, blocks_dense],
                'CRS': spatial_reference,
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                })['OUTPUT']

            snapped_rect = edge_catch(rect_merged, hu_filter_sel, sel_strassen_layer, blocks, spatial_reference, workspace_path)
            save_temp_layer_to_gpkg(snapped_rect,
                                    f"snapped_rect_{str((part_name))}",
                                    workspace_path)



            gaps_colsed = gap_close(snapped_rect, blocks, max_hole_size, max_gap_size, spatial_reference, gap_dist=30)

            patch_removed = patch_remove(gaps_colsed,
                                         sel_hu_layer,
                                         spatial_reference,
                                         workspace_path,
                                         min_patch_size=min_patch_size,
                                         min_bdg_count=min_bdg_count,
                                         footprint_area_sum=6000,
                                         footprint_density_threshold=18)
            save_temp_layer_to_gpkg(patch_removed, f"L_09_patch_removed_{str(part_name)}", workspace_path)


            # Fortschritt aktualisieren
            anz_hu_sum = anz_hu_sum + anz_hu
            prozent = int(anz_hu_sum / anz_hu_gesamt * 100)
            self.dlg.ProgressBar.setValue(prozent)

            merge = processing.run("native:mergevectorlayers", {
                'LAYERS': [patch_removed, merge_layer],
                'CRS': spatial_reference,
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
                })['OUTPUT']
            merge_layer = merge

        save_temp_layer_to_gpkg(merge, "out_global_merge", workspace_path)

        # Load output from previous step
        merge = QgsVectorLayer(os.path.join(workspace_path, "out_global_merge.gpkg"),
                               "merge", "ogr")
        if not merge.isValid():
            logger.log("Failed to load final merge layer", "CRITICAL")
            return

        #gap_fixed = gap_fix(merge, layer_rn, workspace_path)

        # Split the OutputFile into path, filename, and extension
        output_folder, file_with_extension = os.path.split(OutputFile)
        output_filename, _ = os.path.splitext(file_with_extension)
        msg(output_folder)
        msg(output_filename)

        save_temp_layer_to_gpkg(merge, str(output_filename), output_folder + "/")

        logger.log("ERFOLG", "SUCCESS")
